# Site settings
title: SgtSwagrid's Blog
email: your-email@example.com
description: >-
  A developer passionate about open source projects and web development.
  Welcome to my blog where I share my thoughts and projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sgtswagrid.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter
github_username: SgtSwagrid

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "SgtSwagrid"
