title: Alec Dorrington
email: me@alecdorrington.com
description: >-
  A developer passionate about open source projects and web development.
  Welcome to my blog where I share my thoughts and projects.
baseurl: ""
url: "https://alecdorrington.com"
github_username: SgtSwagrid
discord_username: sgtswagrid

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alec Dorrington"
